apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: saas
  name: saas
spec:
  replicas: 3
  selector:
    matchLabels:
      app: saas
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: saas
    spec:
      containers:
      - image: emmanuelo/flask-app:1.6
        name: saas
        resources: {}
status: {}