name: Lint Kubernetes Manifests

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install kubeval for linting
      - name: Install kubeval
        run: |
          wget https://github.com/instrumenta/kubeval/releases/download/0.16.1/kubeval-linux-amd64.tar.gz
          tar xf kubeval-linux-amd64.tar.gz
          sudo mv kubeval /usr/local/bin/

      # Lint all YAML manifests
      - name: Lint manifests
        run: |
          kubeval ./saas/*.yaml
