name: Validate Kubernetes Manifests

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up kubectl
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      # Apply and validate the Kubernetes manifests
      - name: Validate Manifests
        run: |
          kubectl apply --dry-run=client -f ./saas/
